config/routes.rb
# -*- encoding : utf-8 -*-

Cba::Application.routes.draw do

  # Switch locales
  match 'switch_lcoale/:locale' => "home#set_locale", :as => 'switch_locale'
  
  # Switch draft mode
  match 'draft_mode/:mode' => "home#set_draft_mode", :as => 'draft_mode'

  match 'search' => "search#index", :as => 'searches'

  # Comments
  resources :comments, :except => :show
  
  # Tags
  match '/tag/:tag' => "home#tags", :as => 'tags'

  # SiteMenu
  resources :site_menus do
    collection do
      post :sort_menus
    end
  end

  # BLOGS
  resources :blogs do
    member do
      get :delete_cover_picture
    end
    resources :postings do
      member do
        get :delete_cover_picture
      end
      resources :comments
    end
  end
  resources :postings, only: [:show] do
    collection do
      get :tags
    end
  end

  match 'feed' => "home#rss_feed", :as => 'feed'

  # PAGES
  match '/p/:permalink' => 'pages#permalinked', :as => 'permalinked'
  resources :pages do
    member do
      get :delete_cover_picture
      get :sort_components
      post :sort_components
    end
    collection do
      get  :new_article
      post :create_new_article
      get  :templates
    end
    resources :comments
    resources :page_components
  end

  # PAGE TEMPLATES
  resources :page_templates

  # USERS
  match 'registrations' => 'users#index', :as => 'registrations'
  match 'hide_notification/:id' => 'users#hide_notification', :as => 'hide_notification'
  match 'show_notification/:id' => 'users#show_notification', :as => 'show_notification'
  match 'notifications' => 'users#notifications', :as => 'notifications'
  match 'profile/:id'   => 'users#show', :as => 'profile'
  match 'my_group_ids'  => 'users#my_group_ids'

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show,:destroy] do
    resources :invitations    
    resources :user_groups
    resources :user_notifications
    member do
      get :crop_avatar
      put :crop_avatar
      get :edit_role
      put :update_role
      get :details
    end
    collection do
      get :autocomplete_ids
    end
  end

  # AUTHENTICATIONS
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'

  resources :user_notifications do
    collection do
      get :emails
    end
  end

  # ROOT
  root :to => 'home#index'

end

app/models/blog.rb
# -*- encoding : utf-8 -*-

# A Blog is a collection of Postings which may or may not references a
# 'ContentItem' (eg Page).
# When a Blog references a Page, the Page sould be seen as the 'Intro' to
# this blog.

class Blog
  include ContentItem
  acts_as_content_item
  has_cover_picture

  field :allow_comments,        :type => Boolean, :default => true
  field :allow_public_comments, :type => Boolean, :default => true
  field :synopsis
  field :user_role,             :type => Integer, :default => 0

  # REVIEW: Why postings are referenced and not embedded?
  references_many :postings, :dependent => :delete
  validates_associated :postings

  has_and_belongs_to_many :pages, :dependent => :nullify # This pages will be displayed in blog:show
  
  scope :for_role, ->(role) { any_of( 
                                {:user_role.lte => role},
                                {:user_role => nil } 
                              )}
                              
  scope :public_blogs, any_of( 
                   {:user_role => 0},
                   {:user_role => nil} 
                 )
  
  
  # page_tokens are page::object_ids of the pages which should be
  # displayed on the sidebar of this blog.
  def page_tokens=(tokens)
    @pages_before = self.pages.unscoped
    self.pages.nullify
    self.pages.push(Page.criteria.for_ids(tokens).all)
  end

  # Create a posting with attachments from params for current_user
  def create_posting(form_params,current_user)
    posting = self.postings.create(form_params)
    posting.user = current_user
    if posting.save && self.save
      posting.attachments.each(&:save) if posting.attachments
    end
    posting
  end

  # find postings with filter
  #
  # @param [Hash] options a filter to find postings of this blog e.g. '{ is_draft: true }'
  # @return [Criteria] Criteria on self.postings.where( _options_ )
  def scoped_postings(options=nil)
    return self.postings unless options
    self.postings.unscoped.where( options )
  end
  
  # find pages with filter
  # @param [Hash] options a filter to find pages of this blog e.g. '{ is_draft: true }'
  # @return [Criteria] Criteria on self.pages.where( _options_ )
  def scoped_pages(options=nil)
    return self.pages unless options
    self.pages.where( options )
  end
  
  # @return [Boolean] true if user_role is not defined or eql 0
  def public?
    self.user_role == nil || self.user_role == 0
  end

  # @param [User] _user - the current user or nil
  # @param [Symbol] _role - the current user's role
  # @param [Boolean] _draft_mode - select for draft-mode if true
  # @return [Criteria] for all visible postings for this user
  def postings_for_user_and_mode(_user,_draft_mode=false)
    # if no user is given then return only public and online postings
    unless _user
      _online =  self.postings.online.only(:id).map(&:id)
      _public =  self.postings.publics.only(:id).map(&:id) 
      _published=self.postings.published.only(:id).map(&:id) 
      return self.postings.for_ids(_online & _public & _published)
    end

    # if user is moderator and in draft_mode then return all postings
    if _draft_mode && _user.role?(:moderator)
      return self.postings.all
    end

    # The mongo-driver is not able to combine two any_of ($or) as "and"
    #
    # model.any_of( :f1 => '1', :f2 => '2').any_of( :d1 => 'x', :d2 => 'y')
    # is not equal to
    #    select * from model where ( f1 = 1 OR f2 = 2) AND ( d1 = x OR d2 = y ) 
    # but it will act as
    #    select * from model where ( f1 = 1 OR f2 = 2 OR d1 = x OR d2 = y )
    #
    # Posting scopes using any_of are:
    #   * addressed_to(user_id)
    #   * online
    
    # public or addressed to _user
    _addressed_ids = self.postings.addressed_to(_user.id).only(:id).map(&:id)
    # in range of publish_at and enxpire_at
    _online_ids = self.postings.online.only(:id).map(&:id)

    unless _user.role?(:moderator)
      unless _draft_mode
        _visible_ids = _online_ids & self.postings.published.only(:id).map(&:id) & _addressed_ids
      else
        _visible_ids = _addressed_ids
      end
    else
      _visible_ids = _online_ids & self.postings.published.only(:id).map(&:id)
    end

    self.postings.for_ids( _visible_ids )
  end
  

private
  # ContentItems need to override the abstract method but a Blog didn't
  def content_for_intro
    self.synopsis
  end

end

app/controllers/blogs_controller.rb
# -*- encoding : utf-8 -*-

class BlogsController < ApplicationController

  before_filter :ensure_page_tokens, :only => [:update,:create]

  def index
    @blogs = scoped_blogs.all.paginate(
       :page => params[:page],
       :per_page => APPLICATION_CONFIG[:pages_per_page] || 5
     )

     respond_to do |format|
       format.html # index.html.erb
       format.xml  { render :xml => @blogs }
     end
  end

  # Show all postings for this blog
  def show
    @blog = scoped_find(params[:id])

    _postings = @blog.postings_for_user_and_mode(current_user,draft_mode)

    @postings = _postings.desc(:created_at).paginate(:page => params[:page],:per_page => CONSTANTS['paginate_postings_per_page'].to_i)
    respond_to do |format|
      format.js {
         @path = blog_path(@blog, :page => (params[:page] ? (params[:page].to_i+1) : 2) )
      }
      format.html # index.html.erb
      format.xml  { render :xml => @blog }
    end
  end


  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(params[:blog])
    if @blog.save
      redirect_to @blog, :notice => t(:blog_successfully_created)
    else
      render :new
    end
  end

  def edit
    @blog = scoped_find(params[:id])
  end

  def update
    @blog = scoped_find(params[:id])
    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html {
           redirect_to(@blog, :notice => t(:blog_successfully_updated))
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/:id
  # DELETE /blogs/:id.xml
  def destroy
    @blog = scoped_find(params[:id])
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to(blogs_url, :notice => t(:blog_successfully_destroyed)) }
      format.xml  { head :ok }
    end
  end

  # GET /blogs/:id/delete_cover_picture
  def delete_cover_picture
    @blog = scoped_find(params[:id])
    @blog.cover_picture.destroy
    @blog.save
  end

  private
  # page_tokens are provided by checkboxes of the form. Make sure the
  # Array is initialized even if no checkbox is checked.
  def ensure_page_tokens
    params[:blog][:page_tokens] ||= []
  end

  # do a scoped find and raise an Error404 if document not found in scope
  def scoped_find(id)
    begin
      scoped_blogs.find(id)
    rescue
      raise Error404
    end
  end

  # For update and destroy we want to include drafts, so change the default_scope
  def scoped_blogs
    if current_role?(:author)
      Blog.for_role(current_role)
    else
      Blog.published.for_role(current_role)
    end
  end

end

app/helpers/blogs_helper.rb
# -*- encoding : utf-8 -*-

module BlogsHelper
end

app/views/blogs/_blog.haml
%div{:style => 'clear: both'}
= render :partial => '/blogs/blog_intro', :locals => { :blog => blog }

app/views/blogs/_blog_intro.haml
%div{ :class=>:blog_intro, :id=>blog.id.to_s  }
%h1= link_to blog.title, blog
- if blog.is_draft
    %p= t(:is_draft_label)
  
- if blog.cover_picture_exists?
    = render :partial => '/blogs/cover_picture',          |
             :locals => { :blog => blog,                  |
             :format => :thumb,                           |
             :style => 'float:right;margin-left: 10px'}   |

%address{ :style=>'width: 400px; font-style: normal;' }
    %span.item_link_buttons{:id => blog.title.underscore.downcase }
        - if can? :manage, blog
            = ui_button 'edit',  t(:edit), edit_blog_path(blog)
            = ui_button 'destroy', t(:destroy), blog,:confirm => t(:are_you_sure),:method => :delete

= ContentItem::markdown(blog.synopsis) if blog.synopsis

- if params[:action] == 'index'
    %div{ :style => 'float: left; margin-left: 30px; width: 300px; padding: 5px; font-size: 0.8em;' }
        = t(:comments_allowed, :yes_or_no => blog.allow_comments ? t(:allowed) : t(:forbidden) )
        %br
        = t(:public_comments_allowed, :yes_or_no => blog.allow_public_comments ? t(:allowed) : t(:forbidden) )
        %br
        = t(:num_comments, :count => blog.postings.count)


%p{ :style => 'clear: both'}

app/views/blogs/_cover_picture.html.erb
<% style = '' unless defined? style %>
<% if blog.cover_picture %>
  <div class='cover_picture' id='cover_picture_<%= blog.id -%>' style='<%= style -%>'>
      <%= link_to_function( image_tag( w3c_url(blog.cover_picture.url(format||:medium) )),
                 "image_popup('#{w3c_url(blog.cover_picture.url(:popup))}')")
      %>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<%= form_for(blog, :html => { :multipart => true } ) do |f| %>

  <%= errors_for(blog)%>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 80 %>
  </div>

  <div class="field">
    <%= f.label :cover_picture %>
    <%= render(
          :partial => 'cover_picture',
          :locals => { :blog => blog, :format => :thumb, :style => 'display: inline; ' }
        )
    -%>
    <%= f.file_field :cover_picture %>
  </div>
  <div class='field'>
    <%= f.label :delete_picture, sc(:nbsp) %>
    <%= ui_button( 'delete', t(:delete_picture),  delete_cover_picture_blog_path(blog), :remote => true,
        :confirm => t(:are_you_sure)) unless blog.new_record? %>
  </div>

  <div class="field">
    <%= f.label :user_role, t(:necessary_role) %>
    <%= f.select :user_role, options_for_user_role(f.object.user_role) %>
  </div>

  <div class="field">
    <%= f.label :allow_comments %>
    <%= f.check_box :allow_comments %><%= t(:allow_comments) %>
  </div>

  <div class="field">
    <%= f.label :allow_public_comments %>
    <%= f.check_box :allow_public_comments %><%= t(:allow_public_comments) %>
  </div>
  
  <div class="field">
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis, :rows => 5, :cols => 60 %>
  </div>
  

  <div class='field'>
    <%= f.label :page_tokens, t(:sidebar_pages) %>
    <div style='margin-left: 200px;'>
      <% for page in Page.asc(:title) %>
        <%= check_box_tag "blog[page_tokens][]", page.id.to_s, blog.pages.include?(page) %> <%= page.title %><br/>
      <% end %>
    </div>
  </div>
  
  <div class='field'>
    <%= f.label :is_draft, t(:save_as_draft) %>
    <%= f.check_box :is_draft %> <%= t(:will_be_shown_to_authors_only)%>
  </div>
  
  
  <div class='clear'></div>


  <div class="actions">
    <%= f.label :submit, t(:save_changes) %>
    <%= f.submit :class => 'button save' %>
  </div>
<% end %>

app/views/blogs/delete_cover_picture.js.erb
$('#cover_picture_<%= @blog._id -%>').html("<span style='color: red';><%= t(:deleted) -%></span>");

app/views/blogs/edit.haml
- title t(:editing_blog)


= render :partial => 'form', :locals => {:blog => @blog}

- content_for :resource_actions do
  %p= ui_button 'read', t(:read_blog),  @blog
  %p= ui_button 'back', t(:blog_index), blogs_path

app/views/blogs/index.haml
- title t(:blogs), false

- if can? :create, Blog
  - content_for :resource_actions do
    %p= ui_button( 'add', t(:create_new_blog), new_blog_path, :add_class => 'green')


%div
  -if @blogs.total_pages > 1
    .pagination_box= will_paginate @blogs

  - @blogs.each do |blog|
    = render :partial => 'blog_intro', :locals => { :blog => blog }
    %p.content_seperator
  
  -if @blogs.total_pages > 1
    .pagination_box= will_paginate @blogs

app/views/blogs/new.html.erb
<% title t(:new_blog) %>

<%= render :partial => 'form', :locals => {:blog => @blog} %>

<%= link_button t(:blog_index), "button back small", blogs_path %>

app/views/blogs/show.haml
- content_for :resource_actions do
  = ui_button 'back', t(:blog_index), blogs_path
  = ui_button('add', t(:create_new_posting), new_blog_posting_path(@blog), :add_class =>'green' ) if can? :create, Posting
  
- javascript 'endless_page'

%div
  - if @blog.pages.any?
    - content_for :right_column do
      .sidebar-right
        - for page in @blog.pages.where(is_draft: draft_mode)
          = render :partial => 'pages/page_intro', :locals => { :page => page }
          %p.content_seperator

  .left_column
    = render :partial => 'blogs/blog', :locals => { :blog => @blog}
    
    - render_pagination_box @postings
    
    #postings{ style: 'clear: right;'}
      - @postings.each do |posting|
        = render :partial => 'postings/posting', :locals => { :posting => posting, :blog => @blog }
      = render :partial => 'home/load_more', :locals => { :resources => @postings, :path => blog_path(@blog) }
    
    - render_pagination_box @postings
    
    .clear
  .clear

app/views/blogs/show.js.erb
/* REVIEW: This file is needed for any endles-loading view. Is there a way to unify this, so we have it only once? */
/* TODO: Duplication - Posting Header and Links */
$(".pagination").html('<%= escape_javascript(will_paginate(@postings)) %>');

$('.load_more').before( '<div id="page<%= @postings.current_page -%>" style="clear: both; display: none;">'+
                          '<p class="page_seperator"><%= @postings.current_page -%>'+
                          '/<%= @postings.total_pages -%></p>'+
                          '<%= escape_javascript(render(:partial => @postings, :locals => {:blog => @blog})) -%>'+
                          '</div>');

<% if is_on_last_page(@postings) %>
   $('#load_more').html( '<%=  escape_javascript(link_to_function(t(:load_more),"insert_load_button( 'load_more','#{t(:loading)}',"+
        "'#{@path}')", :id => "load_more_link" )) -%>');
   $('#page<%= @postings.current_page -%>').slideDown();
   setTimeout("checkScroll()", 500);
<% else %>
  $('#page<%= @postings.current_page -%>').slideDown();
  $('#load_more').html('<p style="text-align:center; margin-top: 20px;"><%= escape_javascript(t(:end_of_list)) -%></p>');
<% end %>