config/routes.rb
# -*- encoding : utf-8 -*-

Cba::Application.routes.draw do

  # Switch locales
  match 'switch_lcoale/:locale' => "home#set_locale", :as => 'switch_locale'
  
  # Switch draft mode
  match 'draft_mode/:mode' => "home#set_draft_mode", :as => 'draft_mode'

  match 'search' => "search#index", :as => 'searches'

  # Comments
  resources :comments, :except => :show
  
  # Tags
  match '/tag/:tag' => "home#tags", :as => 'tags'

  # SiteMenu
  resources :site_menus do
    collection do
      post :sort_menus
    end
  end

  # BLOGS
  resources :blogs do
    member do
      get :delete_cover_picture
    end
    resources :postings do
      member do
        get :delete_cover_picture
      end
      resources :comments
    end
  end
  resources :postings, only: [:show] do
    collection do
      get :tags
    end
  end

  match 'feed' => "home#rss_feed", :as => 'feed'

  # PAGES
  match '/p/:permalink' => 'pages#permalinked', :as => 'permalinked'
  resources :pages do
    member do
      get :delete_cover_picture
      get :sort_components
      post :sort_components
    end
    collection do
      get  :new_article
      post :create_new_article
      get  :templates
    end
    resources :comments
    resources :page_components
  end

  # PAGE TEMPLATES
  resources :page_templates

  # USERS
  match 'registrations' => 'users#index', :as => 'registrations'
  match 'hide_notification/:id' => 'users#hide_notification', :as => 'hide_notification'
  match 'show_notification/:id' => 'users#show_notification', :as => 'show_notification'
  match 'notifications' => 'users#notifications', :as => 'notifications'
  match 'profile/:id'   => 'users#show', :as => 'profile'
  match 'my_group_ids'  => 'users#my_group_ids'

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show,:destroy] do
    resources :invitations    
    resources :user_groups
    resources :user_notifications
    member do
      get :crop_avatar
      put :crop_avatar
      get :edit_role
      put :update_role
      get :details
    end
    collection do
      get :autocomplete_ids
    end
  end

  # AUTHENTICATIONS
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'

  resources :user_notifications do
    collection do
      get :emails
    end
  end

  # ROOT
  root :to => 'home#index'

end

app/models/user_group.rb
# -*- encoding : utf-8 -*-

class UserGroup
  include Mongoid::Document
  embedded_in  :user
  field        :name,    required: true
  validates_presence_of :name
  field        :members, type: Array, default: []
  # @return String comma-separated string of user-ids
  def member_tokens
    self.members.map{|id| id.to_s}.join(",")
  end
  
  # Split up string by comma and fetch User-ids into member-array
  # @param String comma-separated string of user-ids
  def member_tokens=(new_members)
    _ids = new_members.split(",").map { |id| id.strip }
    self.members = User.any_in( _id: _ids ).only(:_id).all.map{|i| i._id}
    @member_names = nil # clear chached variable
  end
  
  # @return String member names, comma-separated
  def member_names
    @member_names ||= User.any_in( _id: members).only(:name).map(&:name).join(", ")
  end
  
  def users
    User.any_in(_id: members)
  end
  
  # for autocomplete pre-data
  def id_and_name
    users.map {|friend|
      { id: friend.id.to_s, name: friend.name }
    }
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  
  load_and_authorize_resource :user, :user_group
  before_filter :cancel_if_cancel_clicked, only: [:create,:update]
  
  def index
  end
  
  def new
    @user_group = @user.user_groups.build
  end
  
  def create
    @user_group = @user.user_groups.create(params[:user_group])
    if @user_group.valid?
      @user.save
      redirect_to user_user_groups_path(@user), notice: t(:user_group_successfully_created)
    else
      render :new
    end
  end
  
  def edit
    @user_group = @user.user_groups.find(params[:id])
  end
  
  def update
    @user_group = @user.user_groups.find(params[:id])
    @user_group.update_attributes(params[:user_group])
    if @user_group.valid?
      @user.save
      redirect_to user_user_groups_path(@user), notice: t(:user_group_successfully_updated)
    else
      render :new
    end
  end
  
  def destroy
    @user_group = @user.user_groups.find(params[:id])
    @user_group.delete
    @user.save
    redirect_to  user_user_groups_path(@user), notice: t(:user_group_successfully_deleted)
  end
  
private
  def cancel_if_cancel_clicked
    if params[:commit].present? && params[:commit].downcase == t(:cancel).downcase
      redirect_to user_user_groups_path(@user), :notice => t(:canceled)
    end 
  end
end

app/views/user_groups/_form.haml
- content_for :resource_actions do
  = link_to t(:your_groups), user_user_groups_path(@user), :class => 'button back '

%div{:style=>'margin-top: 20px;'}
  = form_for [@user, @user_group] do |f|
  
    = errors_for @user_group
      
    .field
      = f.label :name
      = f.text_field :name
    
    .field
      = f.label :member_tokens
      = f.text_field :member_tokens, "data-pre" => @user_group.id_and_name.to_json 
    
    .field
      = f.label :submit, sc(:nbsp)
      = f.submit :class => 'button save'
      = f.submit :cancel, :class => 'button save'

app/views/user_groups/_user_group.haml
%usergroup
  %blockquote
    %h2= user_group.name
    = user_group.member_names
    %p
      = link_to t(:edit), edit_user_user_group_path(user_group.user,user_group), :class => 'button delete small'
      = link_to t(:delete), user_user_group_path(user_group.user,user_group), method: :delete, confirm: t(:are_you_sure), :class => 'button delete small'
  

app/views/user_groups/edit.haml
- title t(:edit_user_group)

= render 'form'

app/views/user_groups/index.haml
-title t(:user_groups_of, username: @user.name)
- content_for :resource_actions do
  = ui_button 'back', t(:your_profile), user_path(@user)
  = ui_button 'add', t(:add_user_group), new_user_user_group_path(@user), :add_class => 'green'
  
%usergroups
  - if @user.user_groups.any?
    = render @user.user_groups
  - else
    .nothing-found= t(:no_user_group_found)

app/views/user_groups/new.haml
- title t(:new_user_group)

= render 'form'