config/routes.rb
# -*- encoding : utf-8 -*-

Cba::Application.routes.draw do

  # Switch locales
  match 'switch_lcoale/:locale' => "home#set_locale", :as => 'switch_locale'
  
  # Switch draft mode
  match 'draft_mode/:mode' => "home#set_draft_mode", :as => 'draft_mode'

  match 'search' => "search#index", :as => 'searches'

  # Comments
  resources :comments, :except => :show
  
  # Tags
  match '/tag/:tag' => "home#tags", :as => 'tags'

  # SiteMenu
  resources :site_menus do
    collection do
      post :sort_menus
    end
  end

  # BLOGS
  resources :blogs do
    member do
      get :delete_cover_picture
    end
    resources :postings do
      member do
        get :delete_cover_picture
      end
      resources :comments
    end
  end
  resources :postings, only: [:show] do
    collection do
      get :tags
    end
  end

  match 'feed' => "home#rss_feed", :as => 'feed'

  # PAGES
  match '/p/:permalink' => 'pages#permalinked', :as => 'permalinked'
  resources :pages do
    member do
      get :delete_cover_picture
      get :sort_components
      post :sort_components
    end
    collection do
      get  :new_article
      post :create_new_article
      get  :templates
    end
    resources :comments
    resources :page_components
  end

  # PAGE TEMPLATES
  resources :page_templates

  # USERS
  match 'registrations' => 'users#index', :as => 'registrations'
  match 'hide_notification/:id' => 'users#hide_notification', :as => 'hide_notification'
  match 'show_notification/:id' => 'users#show_notification', :as => 'show_notification'
  match 'notifications' => 'users#notifications', :as => 'notifications'
  match 'profile/:id'   => 'users#show', :as => 'profile'
  match 'my_group_ids'  => 'users#my_group_ids'

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show,:destroy] do
    resources :invitations    
    resources :user_groups
    resources :user_notifications
    member do
      get :crop_avatar
      put :crop_avatar
      get :edit_role
      put :update_role
      get :details
    end
    collection do
      get :autocomplete_ids
    end
  end

  # AUTHENTICATIONS
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'

  resources :user_notifications do
    collection do
      get :emails
    end
  end

  # ROOT
  root :to => 'home#index'

end

app/models/user.rb
# -*- encoding : utf-8 -*-

# This is a Device-User-Class extended with ROLES, Avatar-handling, and more
class User
  include Mongoid::Document
  include Mongoid::Spacial::Document # GeoIndex
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  cache

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name
  field :roles_mask, :type => Fixnum, :default => 0
  field :use_gravatar, :type => Boolean, :default => true
  field :invitation_id, :type => BSON::ObjectId
  def invitation
    @invitation ||= Invitation.criteria.for_ids(self.invitation_id).first
  end
  def invitation=(inv)
    @invitation = nil
    self.invitation_id = inv.id
  end

  field :location, type: Array, spacial: true

  def articles
    []
  end

  references_many :authentications, :dependent => :delete
  references_many :postings, :dependent => :delete
  references_many :invitations, :dependent => :delete

  embeds_many :user_notifications
  embeds_many :user_groups
  has_many    :articles

  validates_presence_of   :name
  validates_uniqueness_of :name, :case_sensitive => false
  validates               :email, :presence => true, :email => true
  validates_uniqueness_of :email, :case_sensitive => false


  attr_accessible :name, :email, :password, :password_confirmation, :roles_mask,
                  :remember_me, :authentication_token, :confirmation_token,
                  :avatar, :clear_avatar, :crop_x, :crop_y, :crop_w, :crop_h,
                  :time_zone, :language, :use_gravatar, :invitation_id,
                  :location_token

  attr_accessor :clear_avatar

  has_mongoid_attached_file :avatar,
                            :styles => {
                              :popup  => "800x600=",
                              :medium => "300x300>",
                              :thumb  => "100x100>",
                              :icon   => "64x64"
                            },
                            :processors => [:cropper]
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update  :reprocess_avatar, :if => :cropping?

  # Notifications
  after_create   :async_notify_on_creation
  before_destroy :async_notify_on_cancellation
  before_update  :notify_if_confirmed

  # Authentications
  after_create :save_new_authentication
  after_create :first_user_hook

  # Roles - Do not change the order and do not remove roles if you
  # already have productive data! Thou it's safe to append new roles
  # at the end of the string. And it's safe to rename roles in place
  ROLES = [:guest, :confirmed_user, :author, :moderator, :maintainer, :admin]

  scope :with_role, lambda { |role| { :where => {:roles_mask.gte => ROLES.index(role) } } }

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    paperclip_geometry avatar, style
  end

  def new_avatar?
    if avatar.updated_at && ((Time::now() - Time::at(self.avatar.updated_at)) < 1.minute)
      self.use_gravatar = false
      save
      true
    else
      false
    end
  end

  def admin?
    User.all.any? ? (self == User.first || role?(:admin)) : true
  end

  def role=(role)
    self.roles_mask = ROLES.index(role)
    Rails.logger.warn("SET ROLES TO #{self.roles_mask} FOR #{self.inspect}")
  end

  # return user's role as symbol.
  def role
    self.roles_mask = 0 if self.roles_mask < 0 || self.roles_mask >= ROLES.count
    self.roles_mask ? ROLES[self.roles_mask].to_sym : guest
  end

  # Ask if the user has at least a specific role.
  #   @user.role?('admin')
  def role?(role)
    self.roles_mask >= ROLES.index(role.to_sym)
  end

  # virtual attribute needed for the view but is false always.
  def clear_avatar
    false
  end

  # clear a previous uploaded avatar-image.
  def clear_avatar=(new_value)
    self.avatar = nil if new_value == '1'
  end

  # fetch attributes from the omniauth-record.
  def apply_omniauth(omniauth)
    self.email = omniauth['user_info']['email'] if email.blank?
    apply_trusted_services(omniauth) if self.new_record?
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  # remove the password and password-confirmation attribute if not needed.
  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    super
  end

  # @return String - the URL of the local avatar or the gravatar
  def avatar_url(mode)
    if self.use_gravatar
      "http://gravatar.com/avatar/#{gravatar_id}.png?cache=#{self.updated_at.strftime('%Y%m%d%H%M%S')}"
    else
      avatar.url(mode)
    end
  end

  # Link to the gravatar profile
  def gravatar_profile
    if self.use_gravatar
      "http://gravatar.com/#{gravatar_id}"
    end
  end

  def location_token
    if self.location[:lat].present? && self.location[:lng].present?
      "%3.4f,%3.4f" % [self.location[:lat], self.location[:lng]]
    end
  end

  def location_token=(str)
    coordinates = str.split(",").map! { |a| a.strip.gsub(/\(|\)/,'') }
    self.location = {
      lat: coordinates[0].to_f,
      lng: coordinates[1].to_f
    }
  end

  
private
  def reprocess_avatar
    avatar.reprocess!
  end

  def gravatar_id
    Digest::MD5.hexdigest(self.email.downcase) if self.email
  end

  def apply_trusted_services(omniauth)

    # Merge user_info && extra.user_info
    user_info = omniauth['user_info']
    if omniauth['extra'] && omniauth['extra']['user_hash']
      user_info.merge!(omniauth['extra']['user_hash'])
    end

    # try name or nickname
    if self.name.blank?
      self.name   = user_info['name']   unless user_info['name'].blank?
      self.name ||= user_info['nickname'] unless user_info['nickname'].blank?
      self.name ||= (user_info['first_name']+" "+user_info['last_name']) unless \
        user_info['first_name'].blank? || user_info['last_name'].blank?
    end

    if self.email.blank?
      self.email = user_info['email'] unless user_info['email'].blank?
    end

    # Set a random password for omniauthenticated users
    self.password, self.password_confirmation = String::random_string(20)
    self.confirmed_at, self.confirmation_sent_at = Time.now

    # Build a new Authentication and remember until :after_create -> save_new_authentication
    @new_auth = authentications.build( :uid => omniauth['uid'], :provider => omniauth['provider'])
  end

  # Called :after_create
  def save_new_authentication
    @new_auth.save unless @new_auth.nil?
  end

  # Inform admin about sign ups and cancellations of accounts
  def async_notify_on_creation
     DelayedJob.enqueue('NewSignUpNotifier', Time.now, self.id)
  end

  # Inform admin about cancellations of accounts
  def async_notify_on_cancellation
     DelayedJob.enqueue('CancelAccountNotifier', Time.now, self.inspect)
  end

  # Inform admin if someone confirms an account
  def notify_if_confirmed
    if attribute_changed?('confirmed_at')
      DelayedJob.enqueue('AccountConfirmedNotifier', Time.now, self.id)
    end
  end

  # If created user is first user, confirm and make admin
  def first_user_hook
    if User.count < 2
      self.confirmed_at = Time.now
      self.role=:admin
      self.save!
    end
  end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-

class UsersController < ApplicationController

  load_and_authorize_resource :except => [:hide_notification, :show_notification, :notifications]
  respond_to :html, :js

  def index
    @user_count = User.count
    params[:order] ||= "created_at"
    params[:direction] ||= "asc"
    @users = User.order_by([params[:order].to_sym,params[:direction].to_sym]).reject {|u|
      !can? :read, u
    }.paginate( :page => params[:page],
                :per_page => CONSTANTS['paginate_users_per_page']
              )

    respond_to do |format|
       format.js 
       format.html 
    end
  end

  def show
  end

  def edit_role
    if is_current_user?(@user)
      redirect_to registrations_path, :alert => t(:you_can_not_change_your_own_role)
    end
  end

  def update_role
    @user.update_attributes!(params[:user])
    redirect_to registrations_path, :notice => t(:role_of_user_updated,:user => @user.name)
  end

  def crop_avatar
    if !@user.new_avatar?
      redirect_to @user, :notice => flash[:notice]
    elsif is_in_crop_mode?
      if @user.update_attributes(params[:user])
        if params[:user][:crop_x].present?
          @user.avatar.reprocess!
        end
        render :show
      else
        redirect_to edit_user_path(@user), :error => @user.errors.map(&:to_s).join("<br />")
      end
    end
  end

  def destroy
    @user.delete
    redirect_to registrations_path,
      :notice => t(:user_deleted)
  end

  # GET /hide_notification/:created_at_as_id
  def show_notification
    if user_signed_in?
      ts = Time.at(params[:id].to_i)
      notification = current_user.user_notifications.where(:created_at => ts).first
      unless notification.nil?
        notification.hidden = false
        current_user.save!
        notice = t(:notification_successfully_shown)
        error = nil
      else
        notice = nil
        error = t(:notification_cannot_be_shown)
      end
      redirect_to :back, :notice => notice, :alert => error
    end
  end

  # GET /hide_notification/:created_at_as_id
  def hide_notification
    if user_signed_in?
      ts = Time.at(params[:id].to_i)
      notification = current_user.user_notifications.where(:created_at => ts).first
      unless notification.nil?
        notification.hidden = true
        current_user.save!
        notice = t(:notification_successfully_hidden)
        error = nil
      else
        notice = nil
        error = t(:notification_cannot_be_hidden)
      end
      redirect_to :back, :notice => notice, :alert => error
    end
  end

  def notifications
    @notifications = current_user.user_notifications.unscoped.desc(:created_at)
  end

  def details
    respond_to do |format|
       format.js
       format.html
    end
  end

  def autocomplete_ids
    redirect_to root_path, alert: t(:access_denied) unless current_user
    respond_to do |format|
       format.json { 
         render :json => User.any_of({ name: /#{params[:q]}/i }, { email: /#{params[:q]}/i })
                             .only(:id,:name,:email)
                             .map{ |user| 
                               [
                                 :id   => user.id.to_s, 
                                 :name => user.name + " (#{user.email})"
                               ]
                              }
                             .flatten
       }
     end
  end
  
  def my_group_ids
    redirect_to root_path, alert: t(:access_denied) unless current_user
    respond_to do |format|
       format.json { 
         render :json => current_user.user_groups
                             .map{ |group| 
                               [
                                 :id   => group.id.to_s, 
                                 :name => group.name
                               ]
                              }
                             .flatten
       }
     end
  end

private
  def is_in_crop_mode?
    params[:user] &&
    params[:user][:crop_x] && params[:user][:crop_y] &&
    params[:user][:crop_w] && params[:user][:crop_h]
  end
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-

module UsersHelper # :nodoc:
  
  def options_for_user_role(current=nil)
    options_for_select( (0..(User::ROLES.count-1)).map {|i| [ User::ROLES[i].to_s.humanize, i] }, current )
  end
  
  def order_link_to(field)
    params[:order]     ||= "created_at"
    params[:direction] ||= "asc"
    
    b, _b = params[:order].to_s == field.to_s ? ["<b>", "</b>"] : ["",""]
    link_to( (b+t("by_#{field.to_s}".to_sym)+_b+direction_arrow(field)).html_safe, 
      registrations_path(page: params[:page],
        order: field,
        direction: params[:direction] == "asc" ? "desc" : "asc"
      )
    )
  end
  
private
  def direction_arrow field
    if (params[:order]||"name").to_sym == field
      (params[:direction]||"asc") == "asc" ? " (^)" : " (v)" 
    else
      ""
    end
  end
end

app/views/users/_notifications.haml
- for user_notification in user_notifications
  - present user_notification do |presenter|
    = presenter.head
    = presenter.message_with_buttons

app/views/users/_user.haml
= render :partial => 'userlist_user', :locals => {:user => user}

app/views/users/_user_detail.haml
%li
    %strong= t(:role)+":"
    = user.role.to_s.humanize
    = link_to t(:edit_role), edit_role_user_path(user)
    = '|'
    = link_to t(:cancel_this_account), user_path(user), :confirm => t(:sure?), :method => :delete

- for attribute in user.attributes
    %li{ :style => 'margin-bottom:0px;margin-top: 3px;padding:2px; font-size: 0.8em'}
        %strong= (attribute[0] == "_id" ? "ID" : attribute[0].humanize)+": "
        = user.try(attribute[0].to_s.underscore)

app/views/users/_userlist_user.haml
- present user do |presenter|
  .user
    = presenter.location
    = presenter.avatar
    %h3
      = link_to user.name, user
      - if user == current_user
        %br= ui_button('edit', (t(:you)+sc(:nbsp,:pr,:nbsp)+t(:edit)).html_safe, edit_registration_path(user))
    %div
      = presenter.header
      = presenter.summary
      = presenter.admin_buttons
    .clear

app/views/users/crop_avatar.haml
- title t(:crop_avatar)

%div#cropbox_container
    = image_tag @user.avatar.url(:medium), :id => 'cropbox'

%p
    %em= t(:crop_help)
    
%h4 Preview:
%div{:style => "width:100px; height:100px; overflow: hidden;"}= image_tag @user.avatar.url(:medium), :id => 'preview'

= form_for @user, :url => {:controller => 'users',:action => 'crop_avatar'} do |f| 
    - for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] 
        = f.hidden_field attribute, :id => attribute
    = f.hidden_field :use_gravatar, value: "0"
    %p= f.submit "Crop"

app/views/users/details.haml
- title t(:user_details)

= render :partial => 'user_detail', :locals => { :user => @user }

%p= link_to t(:back), :back

app/views/users/details.js.erb
$('#user_information_<%= @user.id.to_s -%>').html('<%=
  escape_javascript( render :partial => "user_detail", :locals => {:user => @user} )
-%>').show().dialog({
  width: '800px', position: 'center', 
  closeText: 'Close', 
  title: '<%= @user.name -%>',
  dialogClass: 'notice',
  buttons: { "Ok": function() { $(this).dialog("close"); } } 
});

app/views/users/edit_role.haml
- title t(:edit_role_for_user, :user => @user.name ), false

- content_for :resource_actions do
    = ui_button 'details', t(:users_profile), user_path(@user)
    = ui_button 'expand', t(:list_registrations), registrations_path

- if @user.avatar
    = image_tag @user.avatar_url(:thumb), :style=>'float: right;'

%h1= link_to( @user.name, @user )

%div{:style => 'clear: right'}


= form_for(@user, :url => update_role_user_path(@user), :html => { :method => :put }) do |f|
    = render :partial => 'registrations/role', 
             :locals => { :user => @user, :f => f, 
                          :partial_title => "<h2>#{t('userlist.role')}</h2>".html_safe }
    .field
        = f.label :submit, sc(:nbsp).html_safe
        = f.submit :class => 'button save'

app/views/users/index.haml
- title t('userlist.title'),false 
- content_for :head do
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false"
= javascript 'endless_page'

.pagination_box= will_paginate @users

%h2<
    =yield(:title)
    .tiny
        = t(:registered_users_count, :count => @user_count) 
%p
    = t(:sort_by)+":"
    = order_link_to :name
    |
    = order_link_to :email
    |
    = order_link_to :created_at
    |
    = order_link_to :last_sign_in_at
    |
    = order_link_to :sign_in_count
  
%div#user-list
    - for user in @users
        = render user 
        %p{ :style=>'clear: left;' }

    = render :partial => '/home/load_more', :locals => { :resources => @users, :path => registrations_path }

.pagination_box= will_paginate @users

app/views/users/index.js.erb
/* REVIEW: This file is needed for any endles-loading view. Is there a way to unify this, so we have it only once? */
$(".pagination").html('<%= escape_javascript(will_paginate(@users)) %>');

$('.load_more').before( '<div id="page<%= @users.current_page -%>" style="clear: both; display: none;">'+
                          '<p class="page_seperator"><%= @users.current_page -%>'+
                          '/<%= @users.total_pages -%></p>'+
                          '<%= escape_javascript(render(:partial => @users)) -%>'+
                          '</div>');

<% if is_on_last_page(@users) %>
   $('#load_more').html( '<%=  escape_javascript(link_to_function(t(:load_more),"insert_load_button( 'load_more','#{t(:loading)}',"+
        "'#{registrations_path(:page => (params[:page] ? (params[:page].to_i+1) : 2),:order => params[:order].to_sym, :direction => params[:direction].to_sym)}')", :id => "load_more_link" )) -%>');
   $('#page<%= @users.current_page -%>').slideDown();
   setTimeout("checkScroll()", 500);
<% else %>
  $('#page<%= @users.current_page -%>').slideDown();
  $('#load_more').html('<p style="text-align:center; margin-top: 20px;"><%= escape_javascript(t(:end_of_list)) -%></p>');
<% end %>

app/views/users/notifications.haml
- title t(:user_notifications) 

%p= t(:you_have_count_notifications, :count => @notifications.count ) 

#user-notification-list
  - if @notifications.any?
    = render :partial => 'users/notifications', :locals => {:user_notifications => @notifications}

app/views/users/show.haml
- title t("userlist.user_profile", :name => @user.name )

- content_for :resource_actions do
    = ui_button 'expand', t(:list_registrations), registrations_path
    - if current_user && @user == current_user # It's you
        = ui_button( 'edit', (t(:edit_profile) + sc(:nbsp,:pr,:nbsp) + t(:you)).html_safe, edit_registration_path(@user)) 
        = ui_button( 'groups', t(:your_groups), user_user_groups_path(@user))
        
- if @user.avatar
    %div=  link_to_function(     |
       image_tag( w3c_url(@user.avatar_url(:thumb)), :class => "img-with-shadow" ),        |
       "image_popup('#{w3c_url(@user.avatar_url(:popup))}')") |


%div{:style => 'clear: right; margin-top: 10px;'}

    %div{:id => 'users-location-map'}

    %p 
        User: 
        %b= @user.name
    %p 
        Mail: 
        %b= @user.email

- if user_signed_in? && @user == current_user
    - if current_user && current_user.location[:lat].present? && current_user.location[:lng].present?
        %p
            = t(:your_location)+": "
            %span{:id => 'user-location-token'}= current_user.location_token        
                
    - content_for :resource_actions do
        = ui_button 'mail', t(:send_invitaiton), new_user_invitation_path(current_user), :id => 'invitation_link'
      
- else
    - if @user.location[:lat].present? && @user.location[:lng].present?
        = t(:location)+": "
        %span{:id => 'user-location-token'}= @user.location_token
        %br
        
- if current_user.role?(:maintainer)
    %h3{:style=>'clear: both'} Details
    %ul
        = render 'user_detail', :user => @user

- content_for :resource_actions do
    %p{style: 'margin-bottom: 20px;'}= "" # make sure some gap