config/routes.rb
# -*- encoding : utf-8 -*-

Cba::Application.routes.draw do

  # Switch locales
  match 'switch_lcoale/:locale' => "home#set_locale", :as => 'switch_locale'
  
  # Switch draft mode
  match 'draft_mode/:mode' => "home#set_draft_mode", :as => 'draft_mode'

  match 'search' => "search#index", :as => 'searches'

  # Comments
  resources :comments, :except => :show
  
  # Tags
  match '/tag/:tag' => "home#tags", :as => 'tags'

  # SiteMenu
  resources :site_menus do
    collection do
      post :sort_menus
    end
  end

  # BLOGS
  resources :blogs do
    member do
      get :delete_cover_picture
    end
    resources :postings do
      member do
        get :delete_cover_picture
      end
      resources :comments
    end
  end
  resources :postings, only: [:show] do
    collection do
      get :tags
    end
  end

  match 'feed' => "home#rss_feed", :as => 'feed'

  # PAGES
  match '/p/:permalink' => 'pages#permalinked', :as => 'permalinked'
  resources :pages do
    member do
      get :delete_cover_picture
      get :sort_components
      post :sort_components
    end
    collection do
      get  :new_article
      post :create_new_article
      get  :templates
    end
    resources :comments
    resources :page_components
  end

  # PAGE TEMPLATES
  resources :page_templates

  # USERS
  match 'registrations' => 'users#index', :as => 'registrations'
  match 'hide_notification/:id' => 'users#hide_notification', :as => 'hide_notification'
  match 'show_notification/:id' => 'users#show_notification', :as => 'show_notification'
  match 'notifications' => 'users#notifications', :as => 'notifications'
  match 'profile/:id'   => 'users#show', :as => 'profile'
  match 'my_group_ids'  => 'users#my_group_ids'

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users, :only => [:show,:destroy] do
    resources :invitations    
    resources :user_groups
    resources :user_notifications
    member do
      get :crop_avatar
      put :crop_avatar
      get :edit_role
      put :update_role
      get :details
    end
    collection do
      get :autocomplete_ids
    end
  end

  # AUTHENTICATIONS
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications, :only => [:index,:create,:destroy]
  match '/auth/failure' => 'authentications#auth_failure'

  resources :user_notifications do
    collection do
      get :emails
    end
  end

  # ROOT
  root :to => 'home#index'

end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-

class HomeController < ApplicationController
  respond_to :html, :js

  include LayoutHelper #TODO: Why we need this here? (otherwise accessible_postings will not be loaded)

  # Display the top pages on the home-page
  def index
    @blog = Blog.public_blogs.where(:title => t(:news) ).first
    if @blog
      @postings = @blog.postings_for_user_and_mode(current_user,draft_mode)
      .desc(:created_at)
      .paginate(
        :page => params[:page],
        :per_page => CONSTANTS['paginate_postings_per_page'].to_i
      )
    end
    respond_to do |format|
       format.js {
         @path = blog_path(@blog, :page => (params[:page] ? (params[:page].to_i+1) : 2))
         render :index
       }
       format.html { render :index }
    end
  end

  # Respond with an atom rss-feed
  # GET /feed
  def rss_feed
    @feed_items = []
    Blog.public_blogs.each do |blog|
      blog.postings.rss_items.desc(:updated_at).each do |posting|
        if posting.public?
          @feed_items << FeedItem.new(posting.title, posting.body, posting.updated_at, posting_url(posting), posting)
          posting.comments.each do |comment|
            @feed_items << FeedItem.new( ("%s %% %s" % [posting.title,comment.name]), comment.comment, comment.updated_at, posting_url(posting),comment)
          end
        end
      end
    end

    Page.rss_items.asc(:updated_at).each do |page|
      @feed_items << FeedItem.new(page.title,page.body,page.updated_at,page_url(page),page)
      page.comments.each do |comment|
        @feed_items << FeedItem.new( ("%s %% %s" % [page.title,comment.name]), comment.comment, comment.updated_at, page_url(page),comment)
      end
    end

    @feed_items.sort! {|a,b| a.updated_at <=> b.updated_at}
    @feed_items
  end

  # GET /switch_locale/:locale
  def set_locale
    I18n.locale=params[:locale].to_sym
    cookies.permanent[:lang] = params[:locale]
    target = request.env['HTTP_REFERER'] ? request.env['HTTP_REFERER'] : root_path
    redirect_to target, :notice => t(:language_switched_to, :lang => t("locales.#{params[:locale]}")).html_safe
  end

  # GET /draft_mode/:mode
  def set_draft_mode
    change_draft_mode(params[:mode])
    target = request.env['HTTP_REFERER'] ? request.env['HTTP_REFERER'] : root_path
    redirect_to target, :notice => t(:draft_mode_switched_to, :mode => params[:mode] == "1" ? t(:is_on) : t(:is_off)).html_safe
  end
  
  # GET /tag/:tag
  def tags
    @postings ||= accessible_postings(params[:tag],current_role).order([:created_at, :desc])
  end

end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-

module HomeHelper # :nodoc:
  
  # Render a twitter-box if config/twitter.html exists
  def insert_twitter_box
    if File.exist?( filename=File.expand_path("../../../config/twitter.#{Rails.env}.html", __FILE__))
       File.new(filename).read.html_safe
    end
  end
  
  # == Menu structure
  # The main menue, displayed in the #session-div on top of application's layout
  # will _yield_ on 'root-menus' if `SiteMenu.roots.any?` otherwise _yield_ on
  # a 'home-link', 'top-pages', 'blogs', 'userlist', and 'comments'
  #
  # === Note:
  # If a `SiteMenu` exists in the Database-collection only this menue will be
  # displayed and you have to define admin-links like 'blogs', 'userlist', and
  # so on too.
  #
  # === RakeTask:
  # There is a rake-task to generate the default menu in `SiteMenu`
  #
  #     rake data:generate_standard_root_menu
  #
  # @param [boolean] include_children default => true. False will only fetch root-items
  # @param [block] yield this block with every entry
  # @return [array] array of menu-items
  def main_menu(include_children=true,&block)
    menu_items = []
    
    if (root_menus=SiteMenu.roots).any?
      # load menu from database
      root_menus.each do |menu|
        menu_items << yield(menu.name, 
                              render( 'home/menu/with_children', 
                                 :menu => menu, 
                                 :recursive=>include_children,
                                 :force => true
                              )
                            ) if menu && (menu.role_needed||0) <= current_role
      end
    else
      # Use default menu
      
      # home
      menu_items = [ yield(:home, menu_link_to( t("menu.home"), root_path)) ]
      
      # Top pages
      menu_items << top_pages.map { |page|
          yield( page.id.to_s.to_sym, menu_link_to( page.short_title, "/p/#{page.link_to_title}" ))
      } if can? :read, Page
      
      # Blogs, Userlist, Comments
      menu_items << yield(:blogs, menu_link_to( t(:blogs), blogs_path )) if can? :read, Blog
      menu_items << yield(:userlist, menu_link_to( t("menu.userlist"), registrations_path)) if can? :read, Page
      menu_items << yield(:comments, menu_link_to( t("menu.comments"), comments_path)) if can? :read, Comment.new
    end
 
    menu_items
  end
  

end

app/views/home/_action_buttons.haml
-# Tools for the app
= link_to( 'PivotalTracker', pivotal_tracker_project, :target => 'ext_tools') if pivotal_tracker_project
= link_to( 'Github', github_project, :target => 'ext_tools' ) if github_project

-# Actions
= link_to( t(:new_page), new_page_path ) if can? :manage, Page
= link_to( t(:new_blog), new_blog_path ) if can? :manage, Blog
= link_to( t(:manage_templates), templates_pages_path) if can? :manage, PageTemplate
= link_to( t(:manage_menus), site_menus_path) if can? :manage, SiteMenu

-# Communications
= link_to( (twitter_name||'Twitter'), twitter_link, :target => 'ext_tools') if twitter_link

-# Draft Mode
- if current_role?(:author)
  - if session[:draft_mode]
    = link_to t(:hide_drafts), draft_mode_path(0)
  - else
    = link_to t(:show_drafts), draft_mode_path(1)

app/views/home/_interpreter_help.haml
= link_to 'Markdown?', "http://daringfireball.net/projects/markdown/syntax" , :target => :blank
= link_to 'Textile?',  "http://www.textism.com/tools/textile/"              , :target => :blank

app/views/home/_load_more.haml
%p#load_more.load_more
    - if resources.total_pages > resources.current_page
        = link_to_function( t(:load_more),                        |
             "insert_load_button( 'load_more','#{t(:loading)}',"+ |
             "'#{path}?page=#{resources.current_page+1}&order=#{params[:order]}&direction=#{params[:direction]}'"+        |
             ");return false;",                                   |
             :id => 'load_more_link')                             |

app/views/home/index.haml
- title t(:welcome), false
= javascript 'endless_page'

- if can?( :create, Posting ) && @blog
    - content_for :resource_actions do
        %p= ui_button('add', t(:create_new_posting), new_blog_posting_path(@blog), :add_class => 'green')

.column-wrapper

    - if (p=Page.top_pages.where(is_draft: draft_mode)).any?
        - content_for :right_column do
            - for page in p
                = render :partial => 'pages/page_intro', :locals => { :page => page }
                %p.content_seperator
            = insert_twitter_box
    - unless @blog.nil? 
        %p{:style=>'clear: left;'}
        
        %div#postings.left_column
            - render_pagination_box @postings
            - for posting in @postings
                %div{:style=>'clear: right;'}
                = render :partial =>  posting, :locals => { :blog => @blog }
                %p{:style=>'clear: left;'}  
            = render :partial => '/home/load_more', :locals => { :resources => @postings, :path => root_path }
            - render_pagination_box @postings

        %p{:style=>'clear: right;'}
    
    .clear

app/views/home/index.js.erb
/* REVIEW: This file is needed for any endles-loading view. Is there a way to unify this, so we have it only once? */
$(".pagination_box").html('<%= escape_javascript(will_paginate(@postings)) %>');

$('.load_more').before( '<div id="page<%= @postings.current_page -%>" style="clear: both; display: none;">'+
                          '<p class="page_seperator"><%= @postings.current_page -%>'+
                          '/<%= @postings.total_pages -%></p>'+
                          '<%= escape_javascript(render(:partial => @postings, :locals => {:blog => @blog})) -%>'+
                          '</div>');

<% if is_on_last_page(@postings) %>
   $('#load_more').html( '<%=  escape_javascript(link_to_function(t(:load_more),"insert_load_button( 'load_more','#{t(:loading)}',"+
        "'#{@path}')", :id => "load_more_link" )) -%>');
   $('#page<%= @postings.current_page -%>').slideDown();
   setTimeout("checkScroll()", 500);
<% else %>
  $('#page<%= @postings.current_page -%>').slideDown();
  $('#load_more').html('<p style="text-align:center; margin-top: 20px;"><%= escape_javascript(t(:end_of_list)) -%></p>');
<% end %>

app/views/home/tags.haml
- title 'Postings tagged with ' + params[:tag]

#tagged_postings
  = render @postings